[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
PyPlot = "d330b81b-6aea-500a-939a-2ce795aea3ee"
PythonPlot = "274fc56d-3b97-40fa-a1cd-1b4a50311bf9"
